[package]
name = "color-palette"
version = "0.1.0"
edition = "2024"

[dependencies]
color-palette-macros = { path = "./color-palette-macros", optional = true }

[features]
default = ["derive"]
derive = ["dep:color-palette-macros"]
css = ["color-palette-macros/css"]

[workspace]
members = [
    "color-palette-macros",
]
