name: Cargo Test 

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Build & Test
    runs-on: ubuntu-latest   

    steps:
    - uses: actions/checkout@v5

    - name: Rust Cache
      uses: Swatinem/rust-cache@v2

    - name: Check compilation (no features)
      run: cargo check

    - name: Test default (no features)
      run: cargo test

    - name: Test CSS feature only
      run: cargo test --features css

    - name: Test Nix feature only
      run: cargo test --features nix

    - name: Test All Features
      run: cargo test --all-features